import smtplib
from email.message import EmailMessage


def email_alert(subject, body, to):
    msg = EmailMessage()
    msg.set_content(body)
    msg["subject"] = subject
    msg["to"] = to
    msg["from"] = "Name Of User"
    #Name of User is the name of the sender that you want to display

    user = "Email of Sender"
    password = "AutoGeneratedPassword"

    #user is the email address you are using to send the email
    #password is the autogenerated password given by Google

    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()

    server.login(user, password)
    server.send_message(msg)
    server.quit()

for i in range(1):
    if __name__ == "__main__":
        email_alert("Subject Line", "Body Content", "To Email Address")


